server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      # location:  /root/uploadFiles/
      location: E:\\download\\
      max-file-size: 1048576
      max-request-size: 10485760
  # druid连接池
  datasource:
    druid:
      username: root
      password: 1997050812345Xr
      url: jdbc:mysql:///my_caricature?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 47.98.186.6
    port: 5672
    virtual-host: /
    listener:
      simple:
      # 手动ACK 不开启自动ACK模式
        acknowledge-mode: manual
  mail:
    host: smtp.163.com
    username: en2213@163.com
    password: VisT2iiLc
    properties:
      mail:
        smtp:
          auth: true
  # redis
  redis:
    host: 47.98.186.6
    password: VisT2iiLc
    # 连接超时
    timeout: 10000

# mybatis日志
logging:
  level:
    com:
      battcn: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 主键自增回写方法,默认值MYSQL
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: true

# 分页插件
pagehelper:
  helper-dialect: mysql
  params: count
  reasonable: false
  support-methods-arguments: true
